
/* clean up
DROP TABLE NODES;
DROP TABLE LEADERS;
DROP TABLE ARRAYLISTS;
DROP TABLE MAPS;
DROP TABLE TOPICS;
*/

/*
 * 	, status INT
	, description VARCHAR(256)
	, metrics VARCHAR(4096)
 */
CREATE TABLE NODES ( id VARCHAR(128) NOT NULL
	, name VARCHAR(128) NOT NULL
	, nodeGroup VARCHAR(64) NOT NULL
	, ip VARCHAR(64) NOT NULL
	, url VARCHAR(256) NOT NULL
	, attributes VARCHAR(1024)
) ;

CREATE TABLE LEADERS ( id VARCHAR(128) NOT NULL
	, name VARCHAR(128) NOT NULL
	, nodeGroup VARCHAR(64) NOT NULL
) ;

CREATE TABLE ARRAYLISTS (name VARCHAR(128) NOT NULL
	, nodeGroup VARCHAR(64) NOT NULL
	, createdTime BIGINT NOT NULL
	, listIndex INT 
	, listValue VARCHAR(8192) NOT NULL
) ;

CREATE TABLE MAPS (name VARCHAR(128) 
	, nodeGroup VARCHAR(64) NOT NULL
	, createdTime BIGINT NOT NULL
	, mapKey VARCHAR(512) NOT NULL
	, mapValue VARCHAR(8192) NOT NULL
) ;

/*
 * Messaging
 * select * from TOPICS ORDER BY createdTime DESC LIMIT 1
 */
CREATE TABLE TOPICS (name VARCHAR(128) NOT NULL
	, publisherId VARCHAR(128) NOT NULL
	, createdTime BIGINT NOT NULL
	, payload VARCHAR(8192) NOT NULL
);

